import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";

import { Ai40Card, IconAction, palette, ScreenTitle, StatusPill } from "@/components/ai40-ui";
import { ScreenContainer } from "@/components/screen-container";
import { AI_STUDIO_SECTIONS, type StudioFlow } from "@/lib/ai-studio-catalog";

const TONE = { ready: "ready", brief: "neutral", setup: "neutral" } as const;

export default function AiStudioScreen() {
  const router = useRouter();
  const open = (flow: StudioFlow) => {
    if (flow.readiness === "brief") Alert.alert(flow.title, `${flow.output} готовится в режиме «Создать». Фактическая media-generation требует доступного server workflow и отдельного запуска.`);
    router.push(flow.route as never);
  };
  return <ScreenContainer className="px-4" edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><ScrollView contentContainerStyle={styles.content}><ScreenTitle eyebrow="AI40 STUDIO" title="Создать и проверить" action={<IconAction icon="close" label="Закрыть" onPress={() => router.back()} />} /><Ai40Card style={styles.hero}><StatusPill label="Evidence-first" tone="ready" /><Text style={styles.heroTitle}>Одна задача — правильный workflow</Text><Text style={styles.heroText}>Выберите тип результата. AI40 откроет уже готовый workflow или соберёт точный brief для следующего server/CI запуска. Неподключённые возможности не маскируются под выполненные.</Text><Pressable accessibilityRole="button" onPress={() => router.push("/connectors")} style={({ pressed }) => [styles.connectorButton, pressed && styles.pressed]}><MaterialIcons name="settings-input-component" size={18} color="#FFFFFF" /><Text style={styles.connectorButtonText}>Подключения и свежие данные</Text></Pressable></Ai40Card>{AI_STUDIO_SECTIONS.map((section) => <View key={section.id} style={styles.section}><View style={styles.sectionHead}><Text style={styles.sectionTitle}>{section.title}</Text><Text style={styles.sectionCaption}>{section.caption}</Text></View>{section.flows.map((flow) => <Pressable key={flow.id} accessibilityRole="button" onPress={() => open(flow)} style={({ pressed }) => [styles.flowCard, pressed && styles.pressed]}><View style={[styles.iconWrap, { backgroundColor: `${flow.color}18` }]}><MaterialIcons name={flow.icon} size={21} color={flow.color} /></View><View style={styles.flowCopy}><View style={styles.flowHeading}><Text style={styles.flowTitle}>{flow.title}</Text><StatusPill label={flow.label} tone={TONE[flow.readiness]} /></View><Text style={styles.flowSummary}>{flow.summary}</Text><Text style={styles.flowOutput}>{flow.output}</Text></View><MaterialIcons name="chevron-right" size={21} color="#95A0BA" /></Pressable>)}</View>)}</ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { gap: 20, paddingTop: 16, paddingBottom: 32 }, hero: { gap: 9, backgroundColor: "#F0F0FF", borderColor: "#D8D6FF" }, heroTitle: { color: palette.ink, fontSize: 21, lineHeight: 27, fontWeight: "900" }, heroText: { color: palette.muted, fontSize: 13, lineHeight: 19 }, connectorButton: { minHeight: 42, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, borderRadius: 12, backgroundColor: palette.indigo, paddingHorizontal: 14, marginTop: 3 }, connectorButtonText: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" }, section: { gap: 9 }, sectionHead: { gap: 2, paddingHorizontal: 2 }, sectionTitle: { color: palette.ink, fontSize: 16, fontWeight: "900" }, sectionCaption: { color: palette.muted, fontSize: 12, lineHeight: 16 }, flowCard: { flexDirection: "row", alignItems: "flex-start", gap: 11, borderRadius: 16, borderWidth: 1, borderColor: palette.line, backgroundColor: "#FFFFFF", padding: 13 }, iconWrap: { width: 40, height: 40, borderRadius: 13, justifyContent: "center", alignItems: "center" }, flowCopy: { flex: 1, gap: 4 }, flowHeading: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 7 }, flowTitle: { flex: 1, color: palette.ink, fontSize: 14, lineHeight: 19, fontWeight: "900" }, flowSummary: { color: palette.muted, fontSize: 12, lineHeight: 17 }, flowOutput: { color: palette.indigo, fontSize: 11, lineHeight: 15, fontWeight: "800" }, pressed: { opacity: 0.68 } });
